### ISSUE TITLE
Request for Domain Removal from Blacklist: api.getjusto.com

### ISSUE THREAD

**Issue by jaletelier** [oo12/SMBBB#2]
Hello,

I am requesting the removal of our domain, api.getjusto.com, from your blacklist. A past vulnerability on our website allowed unauthorized phishing attempts, but this issue has been fully resolved years ago. 

Since then, we have implemented robust security measures, including patching the vulnerability, enhancing server protections, and conducting regular security audits.

Our domain is critical to our business, and being on the blacklist is causing disruptions. Please review and remove api.getjusto.com from your list. If you need more details, please feel free to contact us to contacto@getjusto.com

Thank you for your help

**Comment by oo12** [comment]
Thanks for getting in touch. Yes, I'll remove that. There used to be an open redirect, but I haven't seen it in our logs since 2021 and I'm glad to hear you've eliminated it.
